### ISSUE TITLE
An error occurs when the terminal command line runs

### ISSUE THREAD

**Issue by Houjingwen** [donglee-afar/logdeep#31]
(python38) houjingwen@MacBook-Pro-2 demo % python3 loganomaly.py train            
Traceback (most recent call last):
  File "loganomaly.py", line 11, in <module>
    from logdeep.models.lstm import loganomaly,deeplog,robustlog
  File "/Users/houjingwen/Desktop/logdeep-master/logdeep/models/lstm.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by ranjianpeng** [comment]
pip install torch?
